### ISSUE TITLE
Hook database upp to app.py, incl HTML changes/additions

### ISSUE THREAD

**Issue by whagestad** [NateBigStone/project04_group_three#40]
Need to get the app to:

- Display bookmarked items (everything in database)
- Save an item to the database
- Delete an item from the database

**Comment by whagestad** [comment]
@NateBigStone 
model.py is ready for implementation into app.py and html files.

add_food(self, food) - will add to the database
get_all_food(self) - will return a list of all rows in the database in a list of food objects
delete_food(self) - will delete from the database

Let me know if I can do anything else on my end, I don't know flask well enough to add these in on the app/html side of things.

**Comment by xm6264jz** [comment]
@whagestad hooked the database correctly. Good job
