### ISSUE TITLE
Create a README

### ISSUE THREAD

**Issue by NateBigStone** [NateBigStone/project04_group_three#9]
* **I'm submitting a ...**
  - [x] feature request

* **What is the current behavior?**

          There is no README

* **What is the expected behavior?**

          There should be a README

* **What is the motivation / use case for changing the behavior?**

          Adding a README will help users know more about our application

* **Add'l Info/Links**
  
  - https://www.makeareadme.com/

**Comment by xm6264jz** [comment]
> * **I'm submitting a ...**
>   
>   * [ ]  bug report
>   * [x]  feature request
> * **What is the current behavior?**
>   ```
>       There is no README
>   ```
> * **What is the expected behavior?**
>   ```
>       There should be a README
>   ```
> * **What is the motivation / use case for changing the behavior?**
>   ```
>       Adding a README will help users know more about our application
>   ```
> * **Add'l Info/Links**
>   
>   * https://www.makeareadme.com/

@NateBigStone do we need another readme.md file. I saw one in the frontend recipe

**Comment by NateBigStone** [comment]
I think it should give a lot more information to the user. The readme I currently have it just notes for us devs to get it running
